/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProductRouteImport } from './routes/product'
import { Route as FindAProviderRouteImport } from './routes/find-a-provider'
import { Route as ExperienceCentersRouteImport } from './routes/experience-centers'
import { Route as DentistsRouteImport } from './routes/dentists'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienceCentersChennaiExpressAvenueRouteImport } from './routes/experience-centers/chennai-express-avenue'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAProviderRoute = FindAProviderRouteImport.update({
  id: '/find-a-provider',
  path: '/find-a-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceCentersRoute = ExperienceCentersRouteImport.update({
  id: '/experience-centers',
  path: '/experience-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistsRoute = DentistsRouteImport.update({
  id: '/dentists',
  path: '/dentists',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceCentersChennaiExpressAvenueRoute =
  ExperienceCentersChennaiExpressAvenueRouteImport.update({
    id: '/chennai-express-avenue',
    path: '/chennai-express-avenue',
    getParentRoute: () => ExperienceCentersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dentists': typeof DentistsRoute
  '/experience-centers': typeof ExperienceCentersRouteWithChildren
  '/find-a-provider': typeof FindAProviderRoute
  '/product': typeof ProductRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/experience-centers/chennai-express-avenue': typeof ExperienceCentersChennaiExpressAvenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dentists': typeof DentistsRoute
  '/experience-centers': typeof ExperienceCentersRouteWithChildren
  '/find-a-provider': typeof FindAProviderRoute
  '/product': typeof ProductRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/experience-centers/chennai-express-avenue': typeof ExperienceCentersChennaiExpressAvenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dentists': typeof DentistsRoute
  '/experience-centers': typeof ExperienceCentersRouteWithChildren
  '/find-a-provider': typeof FindAProviderRoute
  '/product': typeof ProductRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/experience-centers/chennai-express-avenue': typeof ExperienceCentersChennaiExpressAvenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dentists'
    | '/experience-centers'
    | '/find-a-provider'
    | '/product'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/experience-centers/chennai-express-avenue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dentists'
    | '/experience-centers'
    | '/find-a-provider'
    | '/product'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/experience-centers/chennai-express-avenue'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dentists'
    | '/experience-centers'
    | '/find-a-provider'
    | '/product'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/experience-centers/chennai-express-avenue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DentistsRoute: typeof DentistsRoute
  ExperienceCentersRoute: typeof ExperienceCentersRouteWithChildren
  FindAProviderRoute: typeof FindAProviderRoute
  ProductRoute: typeof ProductRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-provider': {
      id: '/find-a-provider'
      path: '/find-a-provider'
      fullPath: '/find-a-provider'
      preLoaderRoute: typeof FindAProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience-centers': {
      id: '/experience-centers'
      path: '/experience-centers'
      fullPath: '/experience-centers'
      preLoaderRoute: typeof ExperienceCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentists': {
      id: '/dentists'
      path: '/dentists'
      fullPath: '/dentists'
      preLoaderRoute: typeof DentistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience-centers/chennai-express-avenue': {
      id: '/experience-centers/chennai-express-avenue'
      path: '/chennai-express-avenue'
      fullPath: '/experience-centers/chennai-express-avenue'
      preLoaderRoute: typeof ExperienceCentersChennaiExpressAvenueRouteImport
      parentRoute: typeof ExperienceCentersRoute
    }
  }
}

interface ExperienceCentersRouteChildren {
  ExperienceCentersChennaiExpressAvenueRoute: typeof ExperienceCentersChennaiExpressAvenueRoute
}

const ExperienceCentersRouteChildren: ExperienceCentersRouteChildren = {
  ExperienceCentersChennaiExpressAvenueRoute:
    ExperienceCentersChennaiExpressAvenueRoute,
}

const ExperienceCentersRouteWithChildren =
  ExperienceCentersRoute._addFileChildren(ExperienceCentersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DentistsRoute: DentistsRoute,
  ExperienceCentersRoute: ExperienceCentersRouteWithChildren,
  FindAProviderRoute: FindAProviderRoute,
  ProductRoute: ProductRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
